language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: LARAVEL='6.*' TESTBENCH='5.6' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: LARAVEL='6.*' TESTBENCH='5.6' COMPOSER_FLAGS='--prefer-stable'
    - php: 8.0
      env: LARAVEL='8.*' TESTBENCH='5.6' COMPOSER_FLAGS='--prefer-lowest'
    - php: 8.0
      env: LARAVEL='8.*' TESTBENCH='5.6' COMPOSER_FLAGS='--prefer-stable'

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
